-- Job-Search Orchestrator — Postgres schema
-- Policy lives in tracking.py: TRANSITIONS / REQUIRES_NOTE are the single
-- authority on legality (see its module docstring). This file carries
-- integrity: types, NOT NULL, FK, UNIQUE.
--
-- ONE narrow exception: jobs.status carries a generated domain CHECK, added
-- by db/apply_schema.py from tracking.status_domain_sql() -- NOT hardcoded
-- here, or it would become a second drifting list. It constrains which
-- values may exist, never which transitions are legal. Reason: raw SQL
-- (the migrator's --wipe re-snapshot, repair scripts) writes status
-- directly, bypassing _apply_transition, so a typo like 'drafcted' would
-- land silently. A loud CheckViolation at write time beats a quiet bad value
-- found later.
--
-- Tables and indexes are created idempotently (IF NOT EXISTS), so
-- db/apply_schema.py can be re-run safely. The app itself never creates
-- schema: storage.ensure_schema only verifies the tables exist.

CREATE TABLE IF NOT EXISTS jobs (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- collection
    source            text NOT NULL,
    external_id       text NOT NULL,
    url               text,
    title             text,
    company           text,
    category          text,
    job_type          text,
    location          text,
    salary            text,
    description       text,
    publication_date  text,         -- source-provided, heterogeneous; kept raw
    fetched_at        timestamptz,  -- system-stamped; normalized to UTC in migration
    content_hash      text,
    -- scoring
    prefilter_pass    integer,
    ladder_match      text,
    relevance_score   integer,
    score_reason      text,
    -- tracking
    status            text NOT NULL DEFAULT 'new',
    status_updated_at timestamptz,
    notes             text,         -- WITHHELD (see db/roles.sql)
    cover_letter      text,         -- WITHHELD
    UNIQUE (source, external_id)
);

CREATE TABLE IF NOT EXISTS job_events (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id      integer NOT NULL REFERENCES jobs(id) ON DELETE RESTRICT,
    from_status text,
    to_status   text NOT NULL,
    at          timestamptz NOT NULL,
    note        text                -- WITHHELD
);

CREATE INDEX IF NOT EXISTS idx_events_job_at ON job_events (job_id, at);
